version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ims_db
      POSTGRES_USER: ims_user
      POSTGRES_PASSWORD: ims_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - app-network

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app  # Removed extra space
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DB_NAME=ims_db
      - DB_USER=ims_user
      - DB_PASSWORD=ims_password
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
      - redis  # Added redis dependency
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
